[project]
name = "project-euler-solutions"
version = "0.1.0"
description = "My solutions to project euler problems"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pymdown-extensions>=10.12",
]

[tool.uv]
dev-dependencies = [
    "mkdocs-material>=9.5.42",
]
